version: "3.8"

services:
  tam_mongo:
    image: mongo:latest
    container_name: tam_mongo
    restart: always
    volumes:
      - db-tam:/data/db
    ports:
      - 27018:27017
    environment:
      - TZ=Asia/Ho_Chi_Minh

      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  tam_redis:
    image: redis:alpine
    container_name: tam_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    environment: 
      - TZ=Asia/Ho_Chi_Minh

volumes:
  db-tam: