const { A_WEEK } = require('../constants');
const { formatNumber } = require('../utils/number');

const {
  PORT = 3000,

  PEPPER,

  MONGO_HOST,
  MONGO_PORT,
  MONGO_DATABASE,
  MONGO_USERNAME,
  MONGO_PASSWORD,

  JWT_SECRET_KEY,
  JWT_EXPIRES_TIME,

  REDIS_PORT = 6379,
  REDIS_HOST,
  REDIS_PASSWORD,

  EMAIL_USERNAME,
  EMAIL_PASSWORD,

  FRONTEND_PAGE_DOMAIN,

  ID_SUFFIX_LENGTH = 6,

  ADMIN_NAME,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
} = process.env;

const MONGO_URI =
  MONGO_USERNAME && MONGO_PASSWORD
    ? `mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin`
    : `mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}`;

const PAGE_NUMBER_DEFAULT = 1;
const PAGE_SIZE_DEFAULT = 10;

module.exports = {
  PORT: PORT || 3000,

  MONGO_URI,

  PEPPER,

  JWT_SECRET_KEY,
  JWT_EXPIRES_TIME: formatNumber(JWT_EXPIRES_TIME, A_WEEK),

  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,

  EMAIL_USERNAME,
  EMAIL_PASSWORD,

  FRONTEND_PAGE_DOMAIN,

  ID_SUFFIX_LENGTH,

  ADMIN_NAME,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,

  PAGE_NUMBER_DEFAULT,
  PAGE_SIZE_DEFAULT,
};
